import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { upsertTopLevelProperty } from "../jsonc";
import {
  findManifestPath,
  loadManifest,
  type ResolvedEntry,
  type ResolvedManifest,
} from "../manifest";
import { propagateContextSecret } from "../dev-vars";
import type { CliEnv, CommandRunner } from "../types";

const GENERATED_HEADER =
  "// Code generated by `gmode sync` from gmode.jsonc. DO NOT EDIT.";

function serviceRegistration(entry: ResolvedEntry): string {
  const service = entry.service!;
  const lines = [
    `  gateway.service(${JSON.stringify(entry.name)}, {`,
    `    mount: ${JSON.stringify(entry.mount)},`,
    `    binding: ${JSON.stringify(entry.binding)},`,
    `    audience: ${JSON.stringify(service.audience ?? entry.name)},`,
  ];
  if (service.auth !== undefined) lines.push(`    auth: ${service.auth},`);
  if (service.scopes && service.scopes.length > 0) {
    lines.push(`    scopes: ${JSON.stringify(service.scopes)},`);
  }
  lines.push(`    openapi: ${service.openapi ?? true},`);
  lines.push("  });");
  return lines.join("\n");
}

function webRegistration(entry: ResolvedEntry): string {
  const webApp = entry.webApp!;
  const lines = [
    `  gateway.web(${JSON.stringify(entry.name)}, {`,
    `    mount: ${JSON.stringify(entry.mount)},`,
    `    binding: ${JSON.stringify(entry.binding)},`,
  ];
  const apiMount = webApp.api?.mount ?? "/api";
  const apiOpenapi = webApp.api?.openapi ?? true;
  if (webApp.api !== undefined) {
    lines.push(
      `    api: { mount: ${JSON.stringify(apiMount)}, openapi: ${apiOpenapi} },`,
    );
  }
  lines.push("  });");
  return lines.join("\n");
}

/** Render `src/gmode.generated.ts` for the gateway Worker. */
export function renderGeneratedModule(resolved: ResolvedManifest): string {
  const services = resolved.entries.filter((e) => e.kind === "service");
  const webApps = resolved.entries.filter((e) => e.kind === "web");

  const envLines: string[] = [];
  for (const entry of resolved.entries) {
    envLines.push(
      `  /** ${entry.kind === "web" ? "Web app" : "Service"} binding for "${entry.name}" (worker: ${entry.workerName}). */`,
      `  ${entry.binding}: FetcherLike;`,
    );
  }
  envLines.push(
    "  /** Shared HMAC secret used to sign the private gateway context. */",
    "  GMODE_CONTEXT_SECRET?: string;",
  );

  const registrations = [
    ...services.map(serviceRegistration),
    ...webApps.map(webRegistration),
  ].join("\n\n");

  return `${GENERATED_HEADER}
import type { FetcherLike } from "@gmode/core";
import type { Gateway } from "@gmode/gateway";

/** Gateway env bindings derived from gmode.jsonc. Extend with \`GmodeEnv & { ... }\`. */
export type GmodeEnv = {
${envLines.join("\n")}
};

/**
 * Register every service and web app declared in gmode.jsonc.
 *
 * Call once after \`createGateway()\`; binding names and mounts stay in sync
 * with the manifest so they never drift from wrangler.jsonc.
 */
export function registerServices<Env extends GmodeEnv>(
  gatewayIn: Gateway<Env>,
): Gateway<Env> {
  const gateway = gatewayIn as unknown as Gateway<GmodeEnv>;
${registrations || "  // No services or web apps declared in gmode.jsonc yet."}
  return gatewayIn;
}
`;
}

/** Render the wrangler `services` array value for the gateway config. */
export function renderWranglerServices(resolved: ResolvedManifest): string {
  if (resolved.entries.length === 0) return "[]";
  const items = resolved.entries.map(
    (entry) =>
      `    {\n      "binding": ${JSON.stringify(entry.binding)},\n      "service": ${JSON.stringify(entry.workerName)}\n    }`,
  );
  return `[\n${items.join(",\n")}\n  ]`;
}

export type SyncResult = {
  resolved: ResolvedManifest;
  wroteWrangler: boolean;
  wroteGenerated: boolean;
  updatedServiceSecrets: string[];
};

/** Run the manifest sync engine against a workspace. */
export function runSync(startDir: string): SyncResult {
  const manifestPath = findManifestPath(startDir);
  if (!manifestPath) {
    throw new Error(
      `No ${"gmode.jsonc"} found in ${startDir} or any parent directory. Run \`gmode init\` first.`,
    );
  }
  const resolved = loadManifest(manifestPath);

  // 1. Sync the gateway wrangler.jsonc `services` array.
  const wranglerPath = ["wrangler.jsonc", "wrangler.json"]
    .map((f) => join(resolved.gatewayDir, f))
    .find((p) => existsSync(p));
  if (!wranglerPath) {
    throw new Error(
      `Gateway has no wrangler.jsonc: ${resolved.gatewayDir}`,
    );
  }
  const wranglerText = readFileSync(wranglerPath, "utf8");
  const nextWrangler = upsertTopLevelProperty(
    wranglerText,
    "services",
    renderWranglerServices(resolved),
  );
  const wroteWrangler = nextWrangler !== wranglerText;
  if (wroteWrangler) {
    writeFileSync(wranglerPath, nextWrangler, "utf8");
  }

  // 2. Generate the typed registration module.
  const generatedPath = join(resolved.gatewayDir, "src", "gmode.generated.ts");
  const generated = renderGeneratedModule(resolved);
  const existing = existsSync(generatedPath)
    ? readFileSync(generatedPath, "utf8")
    : undefined;
  const wroteGenerated = existing !== generated;
  if (wroteGenerated) {
    writeFileSync(generatedPath, generated, "utf8");
  }

  const updatedServiceSecrets = propagateContextSecret(resolved);

  return { resolved, wroteWrangler, wroteGenerated, updatedServiceSecrets };
}

export const sync: CommandRunner = async (_args, cli: CliEnv) => {
  try {
    const result = runSync(cli.cwd);
    const { resolved } = result;
    cli.stdout(
      `Synced ${resolved.entries.length} entr${resolved.entries.length === 1 ? "y" : "ies"} from gmode.jsonc`,
    );
    for (const entry of resolved.entries) {
      cli.stdout(
        `  ${entry.kind === "web" ? "web    " : "service"} ${entry.name.padEnd(16)} ${entry.mount.padEnd(12)} -> ${entry.binding} (${entry.workerName})`,
      );
    }
    cli.stdout(
      result.wroteWrangler
        ? "Updated gateway wrangler services bindings."
        : "Gateway wrangler services bindings already up to date.",
    );
    cli.stdout(
      result.wroteGenerated
        ? "Wrote gateway src/gmode.generated.ts."
        : "gateway src/gmode.generated.ts already up to date.",
    );
    if (result.updatedServiceSecrets.length > 0) {
      cli.stdout(
        `Propagated GMODE_CONTEXT_SECRET to: ${result.updatedServiceSecrets.join(", ")}`,
      );
    }
    return 0;
  } catch (err) {
    cli.stderr(err instanceof Error ? err.message : String(err));
    return 1;
  }
};
