// Code generated by `gmode sync` from gmode.jsonc. DO NOT EDIT.
import type { FetcherLike } from "@gmode/core";
import type { Gateway } from "@gmode/gateway";

/** Gateway env bindings derived from gmode.jsonc. Extend with `GmodeEnv & { ... }`. */
export type GmodeEnv = {
  /** Service binding for "users" (worker: gmode-example-web-users). */
  USERS_API: FetcherLike;
  /** Web app binding for "dashboard" (worker: gmode-example-web-dashboard). */
  DASHBOARD_APP: FetcherLike;
  /** Shared HMAC secret used to sign the private gateway context. */
  GMODE_CONTEXT_SECRET?: string;
};

/**
 * Register every service and web app declared in gmode.jsonc.
 *
 * Call once after `createGateway()`; binding names and mounts stay in sync
 * with the manifest so they never drift from wrangler.jsonc.
 */
export function registerServices<Env extends GmodeEnv>(
  gatewayIn: Gateway<Env>,
): Gateway<Env> {
  const gateway = gatewayIn as unknown as Gateway<GmodeEnv>;
  gateway.service("users", {
    mount: "/users",
    binding: "USERS_API",
    audience: "users",
    openapi: true,
  });

  gateway.web("dashboard", {
    mount: "/app",
    binding: "DASHBOARD_APP",
    api: { mount: "/api", openapi: true },
  });
  return gatewayIn;
}
